### PR TITLE
Correcting wrong or missing op_codes display

### LINKED ISSUE #1210: wrong script opcode display
### Description

i noticed some opcodes are displayed wrong, so i made a transaction to display all opcodes except `01`-`4b` and pushdata{1,2,4} (because they take the data after them)

#### Version

latest

### Steps to reproduce

lock coins up with scriptPubKey `004f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff`

(node js to generate: `Buffer.from(Array(2**8-78).fill().map((x,i)=>i+(i?78:0))).toString('hex')`)

### Screenshots

`OP_PUSHNUM` in front of every opcode that *starts* with a number
image
image
checkmultisigverify without color
image
greaterthanorequal without color
image
inconsistency between `OP_0` and `OP_PUSHBYTES_1 1`
image
checksequenceverify without color
image

#### Additional info

using romanz/electrs backend

### PR DESCRIPTION
**Pull request by softsimon**
fixes #1210

Using the specially crafted Testnet transaction `88710a9a6751827490f260e307757543f533c0f18bcd6865794713d263d5f5a4` by @antonilol I have corrected the erroneously displayed OP_CODES when running bitcoin core that did not match the RustBitcoin Esplora style.

I also restored the `multisig` transaction output type support.

Before
```
OP_PUSHBYTES_1 -1
OP_PUSHBYTES_1 1
```
After
```
OP_PUSHNUM_NEG1
OP_PUSHNUM_1
```

Before
```
OP_PUSHNUM_2DROP
OP_PUSHNUM_2DUP
```
After
```
OP_2DROP
OP_2DUP
```

Before
```
OP_CHECKLOCKTIMEVERIFY
```
After:
```
OP_CLTV
```

### CODE REVIEW

File: backend/src/api/bitcoin/bitcoin-api.ts [hunk 1]
```diff
@@ -294,15 +295,28 @@ class BitcoinApi implements AbstractBitcoinApi {
...
+          const chunkInt = parseInt(chunk, 10);
+          if (chunkInt < 0) {
+            b.push('OP_PUSHNUM_NEG' + -chunkInt);
+          } else {
+            b.push('OP_PUSHNUM_' + chunk);
+          }
         } else {
-          b.push('OP_PUSHBYTES_' + Math.round(chunk.length / 2) + ' ' + chunk);
+          const dataLength = Math.round(chunk.length / 2);
+          if (dataLength > 75) {
```
Comment (antonilol) [inline backend/src/api/bitcoin/bitcoin-api.ts:315]: If the chunk length is larger than 255, OP_PUSHDATA2 is used (and when larger than 65535 OP_PUSHDATA4 but it is never used because bitcoin doesnt allow pushes larger than 520 bytes)

**Comment by antonilol** [comment]
my transaction is 88710a9a6751827490f260e307757543f533c0f18bcd6865794713d263d5f5a4, the one you have in your comment is a bare multisig of 7 years ago

**Comment by antonilol** [comment]
this doesnt fix the color issue and the inconsistency between `OP_0` and `OP_PUSHBYTES_1 1` (https://github.com/mempool/mempool/issues/1210#issue-1122104796)

**Comment by softsimon** [comment]
> this doesnt fix the color issue and the inconsistency between `OP_0` and `OP_PUSHBYTES_1 1` ([#1210 (comment)](https://github.com/mempool/mempool/issues/1210#issue-1122104796))

Frontend coloring will be fixed in a separate PR

**Review by antonilol — APPROVED** [review]
Looks good to me!
